image: node

cache:
  paths:
    - node_modules/
    - .yarn
    - .cache

stages:
  - test

before_script:
  - apt-get update -qq && apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  - yarn

test:
  image: buildkite/puppeteer
  stage: test
  script:
    - yarn lint
    - yarn test
